exclude_paths:
  - '/vendor/*'

engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: 'php'
      standard: 'PSR1,PSR2,PHPCS'
  phpmd:
    enabled: true
    config:
      file_extensions: 'php'
      rulesets: 'unusedcode'

ratings:
  paths:
    - '**.php'
