<?php
declare(strict_types=1);

namespace Gdbots\Bundle\AppBundle\Composer;

use Composer\Script\Event;
use Symfony\Component\Filesystem\Filesystem;

class ScriptHandler
{
    /**
     * @var array
     */
    protected static $options = [
        'gdbots-app' => [
            'constants-file' => '.constants.php',
            'version'        => null,
        ],
    ];

    /**
     * Creates a file which defines constants for use in the app kernel.
     *
     * @param Event $event
     */
    public static function installConstantsFile(Event $event)
    {
        $version = $event->getComposer()->getPackage()->getPrettyVersion();
        $options = array_merge(static::$options, $event->getComposer()->getPackage()->getExtra());
        if (!isset($options['gdbots-app']['constants-file'])) {
            $options['gdbots-app']['constants-file'] = static::$options['gdbots-app']['constants-file'];
        }

        if (null === $version && isset($options['gdbots-app']['version'])) {
            $version = $options['gdbots-app']['version'];
        }

        static::$options['gdbots-app']['constants-file'] = $constantsFile = $options['gdbots-app']['constants-file'];

        $now = new \DateTime();
        list($appVendor, $appName) = explode('/', $event->getComposer()->getPackage()->getName());
        $appRootDir = realpath(getcwd());
        $appVersion = $version ?: static::getAppVersion($appRootDir, $now);
        $appBuild = self::getAppBuild($now);
        $appDeploymentId = self::getAppDeploymentId() ?: $appBuild;
        $appDevBranch = static::getAppDevBranch($appRootDir);
        $systemMacAddress = static::getSystemMacAddress();
        $cloudProvider = self::getCloudProvider();
        $cloudRegion = self::getCloudRegion();
        $cloudZone = self::getCloudZone();
        $cloudInstanceId = self::getCloudInstanceId();
        $cloudInstanceType = self::getCloudInstanceType();

        $constants = [
            'app_vendor'          => $appVendor,
            'app_name'            => $appName,
            'app_version'         => $appVersion,
            'app_build'           => $appBuild,
            'app_deployment_id'   => $appDeploymentId,
            'app_dev_branch'      => $appDevBranch,
            'system_mac_address'  => $systemMacAddress,
            'cloud_provider'      => $cloudProvider,
            'cloud_region'        => $cloudRegion,
            'cloud_zone'          => $cloudZone,
            'cloud_instance_id'   => $cloudInstanceId,
            'cloud_instance_type' => $cloudInstanceType,
            'constants_file'      => $constantsFile,
        ];

        $event->getIO()->write(sprintf('<info>Writing constants to "%s"</info>', $appRootDir . '/' . $constantsFile));
        $customText = self::appendToConstantsFile($constants);
        $text = <<<TEXT
<?php
/**
 * DO NOT EDIT THIS FILE as it will be overwritten by Composer as part of
 * the installation/update process or by Chef/Rightscale/CodeDeploy/etc.
 *
 * Generated at {$now->format('c')} by composer
 *
 * @see \Gdbots\Bundle\AppBundle\AppKernel
 */
define('APP_VENDOR', '$appVendor');
define('APP_NAME', '$appName');
define('APP_VERSION', '$appVersion');
define('APP_BUILD', '$appBuild');
define('APP_DEPLOYMENT_ID', '$appDeploymentId');
define('APP_DEV_BRANCH', '$appDevBranch');
define('APP_ROOT_DIR', realpath(__DIR__));
define('SYSTEM_MAC_ADDRESS', '$systemMacAddress');
define('CLOUD_PROVIDER', '$cloudProvider');
define('CLOUD_REGION', '$cloudRegion');
define('CLOUD_ZONE', '$cloudZone');
define('CLOUD_INSTANCE_ID', '$cloudInstanceId');
define('CLOUD_INSTANCE_TYPE', '$cloudInstanceType');

{$customText}

TEXT;

        $fs = new Filesystem();
        $fs->dumpFile($constantsFile, $text);
    }

    /**
     * Override in your own script handler to customize.
     * Keep in mind that if you're using Chef, Opsworks, etc. to generate
     * this file during an external build process then whatever you do here
     * should probably be done there too.
     *
     * @param array $constants
     *
     * @return string
     */
    protected static function appendToConstantsFile(array $constants): string
    {
        return <<<TEXT
/**
 * Need to append your own constants?  Operators are standing by...
 * @see \Gdbots\Bundle\AppBundle\Composer\ScriptHandler::appendToConstantsFile
 */
//define('MY_SPECIAL_CONST', 'build-{$constants['app_build']}';
TEXT;
    }

    /**
     * Attempts to find the version of the app using git rev-parse, svnversion and
     * finally just using the timestamp as a last resort.
     *
     * This is ONLY called if the composer.json extra config "['gdbots-app']['version']" has
     * not been set.
     *
     * @param string    $appRootDir
     * @param \DateTime $date
     *
     * @return string
     */
    protected static function getAppVersion(string $appRootDir, \DateTime $date): string
    {
        $fs = new Filesystem();

        if ($fs->exists('.git/refs/heads/master')) {
            ob_start();
            passthru('git rev-parse --short HEAD 2>&1');
            $version = trim(ob_get_clean());

            if (!empty($version) && false === strpos($version, 'fatal')) {
                return 'v' . $version;
            }
        }

        if ($fs->exists('.svn/entries')) {
            ob_start();
            passthru("svnversion $appRootDir 2>&1");
            $version = (int)trim(ob_get_clean());
            if (!empty($version)) {
                return 'v' . $version;
            }
        }

        return 'v' . $date->format('YmdHis');
    }

    /**
     * Determines the build of the application.
     *
     * @param \DateTime $date
     *
     * @return string
     */
    protected static function getAppBuild(\DateTime $date): string
    {
        return getenv('APP_BUILD') ?: $date->format('YmdHis');
    }

    /**
     * Determines the deployment id of the application.
     *
     * @return string
     */
    protected static function getAppDeploymentId(): ?string
    {
        return getenv('APP_DEPLOYMENT_ID') ?: null;
    }

    /**
     * Attempts to get the currently active dev branch from git
     * and then from svn.  if those fail, just return 'master'.
     *
     * @param string $appRootDir
     *
     * @return string
     */
    protected static function getAppDevBranch(string $appRootDir): string
    {
        $fs = new Filesystem();

        if ($fs->exists('.git/refs/heads/master')) {
            return static::getCurrentGitBranch($fs);
        }

        if ($fs->exists('.svn/entries')) {
            return static::getCurrentSvnBranch($appRootDir);
        }

        return 'master';
    }

    /**
     * @param Filesystem $fs
     *
     * @return string
     */
    protected static function getCurrentGitBranch(Filesystem $fs): string
    {
        ob_start();
        passthru('git symbolic-ref --short HEAD 2>&1');
        $branch = trim(ob_get_clean());

        if (false !== strpos($branch, 'fatal')) {
            return 'master';
        }

        return $fs->exists('.git/refs/heads/' . $branch) ? $branch : 'master';
    }

    /**
     * @param string $appRootDir
     *
     * @return string
     */
    protected static function getCurrentSvnBranch(string $appRootDir): string
    {
        ob_start();
        passthru("svn info $appRootDir 2>&1");
        $lines = explode(PHP_EOL, ob_get_clean());
        foreach ($lines as $line) {
            if (empty($line) || false === strpos($line, 'URL:')) {
                continue;
            }

            return trim(strrev(explode('/', strrev($line))[0]));
        }

        return 'trunk';
    }

    /**
     * Returns the system node ID
     *
     * @return string
     */
    protected static function getSystemMacAddress(): ?string
    {
        static $node = null;
        if (null !== $node) {
            return $node;
        }

        $node = getenv('SYSTEM_MAC_ADDRESS') ?: null;
        if (null !== $node) {
            return $node;
        }

        $pattern = '/[^:]([0-9A-Fa-f]{2}([:-])[0-9A-Fa-f]{2}(\2[0-9A-Fa-f]{2}){4})[^:]/';
        $matches = [];

        // search the ifconfig output for all MAC addresses and return the first one found
        if (preg_match_all($pattern, static::getIfconfig(), $matches, PREG_PATTERN_ORDER)) {
            $node = $matches[1][0];
            $node = str_replace(':', '', $node);
            $node = str_replace('-', '', $node);
        }

        return $node;
    }

    /**
     * Returns the network interface configuration for the system
     *
     * @codeCoverageIgnore
     *
     * @return string
     */
    protected static function getIfconfig(): ?string
    {
        ob_start();
        switch (strtoupper(substr(php_uname('a'), 0, 3))) {
            case 'WIN':
                passthru('ipconfig /all 2>&1');
                break;
            case 'DAR':
                passthru('ifconfig 2>&1');
                break;
            case 'LIN':
            default:
                passthru('netstat -ie 2>&1');
                break;
        }

        return ob_get_clean();
    }

    /**
     * @return string
     */
    protected static function getCloudProvider(): string
    {
        return getenv('CLOUD_PROVIDER') ?: 'private';
    }

    /**
     * @return string
     */
    protected static function getCloudRegion(): string
    {
        return getenv('CLOUD_REGION') ?: '';
    }

    /**
     * @return string
     */
    protected static function getCloudZone(): string
    {
        return getenv('CLOUD_ZONE') ?: '';
    }

    /**
     * @return string
     */
    protected static function getCloudInstanceId(): ?string
    {
        return getenv('CLOUD_INSTANCE_ID') ?: static::getSystemMacAddress();
    }

    /**
     * @return string
     */
    protected static function getCloudInstanceType(): string
    {
        return getenv('CLOUD_INSTANCE_TYPE') ?: '';
    }
}
